# Generated by Django 2.2.5 on 2019-10-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('grupo_amigo', models.CharField(max_length=100)),
            ],
        ),
    ]
